[package]
name = "mark_duplicates"
version = "0.2.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
bzip2 = "0.5"
rayon = "1.8"
clap = { version = "4.5", features = ["derive", "std"], default-features = false }
