[package]
name = "process_vsearch_cluster_output"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
clap = { version = "4.5", features = ["derive", "std", "help"], default-features = false }

[dev-dependencies]
flate2 = "1.0"
