name: Python Unit Tests

on:
  pull_request: # Runs on all PRs

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check for relevant changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - '**/*.py'
              - '.github/workflows/pytest.yml'

      - name: Setup Python environment
        if: steps.filter.outputs.python == 'true'
        uses: ./.github/actions/setup-python
        with:
          additional_requirements: post-processing/deps/nao_dedup/requirements-dev.txt

      - name: Set up Rust
        if: steps.filter.outputs.python == 'true'
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run pytest
        if: steps.filter.outputs.python == 'true'
        run: |
          python -m pytest bin/test_*.py modules/local/*/resources/usr/bin/test_*.py post-processing/tests/ -v --tb=short
